openapi: 3.1.0
info:
  version: 1.0.0
  title: Petstore API
  description: |
    Этот API предоставляет функциональность для работы с магазином домашних животных.
    С помощью этого API можно управлять питомцами, их данными, а также выполнять
    операции поиска, добавления, обновления и удаления питомцев.
    **Особенности**:
    - Работает с данными о питомцах (имя, возраст, тип и т.д.).
    - Позволяет обновлять и удалять записи о питомцах.
    - Предоставляет возможность поиска питомцев по уникальному ID.
    
    API поддерживает аутентификацию через **API ключи** и использует **OAuth2** для защиты некоторых путей.
servers:
  - url: https://httpbin.org
paths:
  '/pet/{id}':
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
        - pet
      summary: Update a pet
      description: This operation will update a pet in the database.
      responses:
        '400':
          description: Invalid id value
      security:
        - apiKey: []
    get:
      tags:
        - pet
      summary: Find a pet
      description: This operation will find a pet in the database.
      responses:
        '400':
          description: Invalid status value
      security: []
components:
  securitySchemes:
    apiKey:
      type: http
      scheme: basic
